import Navbar from "@/components/Navbar";
import { dbConnect } from "@/services/mongo";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Event Management App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang='en'>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
        <main className='py-8'>{children}</main>
      </body>
    </html>
  );
}
